### ISSUE TITLE
Error in downloading Open-Images dataset

### ISSUE THREAD

**Issue by akshitac8** [hbdat/cvpr20_LESA#1]
Hello @hbdat,

Hope you are doing great, I was trying to download the open-images dataset but there is no annotations-human.csv file available in 2017_11 folder. It would be really helpful if you could share the file 😄

**Comment by hbdat** [comment]
Hi Akshita,

Thanks for raising the issue.
You can download the annotation from this link:
https://storage.googleapis.com/openimages/2017_11/annotations_human_2017_11.tar.gz

Best,
Dat

**Comment by akshitac8** [comment]
Hi Dat,

Thank you for uploading the files.
I also want to ask, In the open-images image downloading script 2017_11 folder is mentioned and while feature extraction 2018_04 mentioned. So, We need to download from both folders merge them into one and then use?

Best,
Akshita

**Comment by hbdat** [comment]
The classes-trainable.txt and class-description.csv could be downloaded from:
https://storage.googleapis.com/openimages/2017_11/classes_2017_11.tar.gz
Thanks again for spotting the missing files.
