### ISSUE TITLE
function not found "evaluate_zs_df_OpenImage"

### ISSUE THREAD

**Issue by akshitac8** [hbdat/cvpr20_LESA#2]
Hi @hbdat,

I was trying to train the open-images dataset but I was not able to find the evaluate function for the same.
I also wanted to ask, the training images are taken from 5 million images with trainable classes?

Regards,
Akshita

**Comment by hbdat** [comment]
Hi Akshita,

Thanks again for letting me know about this missing function.
I have added the evaluation function ‘evaluate_zs_df_OpenImage’ in the ‘core.utils’ file (please see the latest commit)

For the training images, yes, we only use images with trainable classes.

Best,
Dat
