### ISSUE TITLE
missing file or misspelled file name  

### ISSUE THREAD

**Issue by SolaleT** [hbdat/cvpr20_LESA#5]
Thank you for sharing the code. 
In the "extract_data" folder, there is no file with the name "extract_full_NUS_WIDE_images_attention_VGG_feature_2_TFRecord.py", which according to the instruction is needed for extracting features into TensorFlow storage format. Could you please clarify whether this is a typo error or the actual file is missing from this repo.

**Comment by hbdat** [comment]
Hi @SolaleT,

Thanks for raising this issue.
I believe this is a misspelled issue.
It should be ```extract_full_NUS_WIDE_images_VGG_feature_2_TFRecord.py``` instead of ```extract_full_NUS_WIDE_images_attention_VGG_feature_2_TFRecord.py```.
I have corrected this in the latest commit.

Best,
Dat
