### ISSUE TITLE
Why do you use 'vecs = pickle.load(infile)[1]' in file 'multilabel_experiments/NUS_WIDE_rank_Visual_Word_Attention.py'

### ISSUE THREAD

**Issue by jingcaiguo** [hbdat/cvpr20_LESA#7]
We knonw that in line 67-68 of 'NUS_WIDE_rank_Visual_Word_Attention.py', 'pickle.load(infile)[1]' means the word vectors of unseen classes.

So, i am a little confused why do you only use unseen classes when training the attention?

**Comment by hbdat** [comment]
Hi @jingcaiguo ,

Thanks for reaching out.

The script "multilabel_experiments/NUS_WIDE_rank_Visual_Word_Attention.py" is used for multi-label learning (which we report in the supplementary material) and not the main multi-label zero-shot learning experiments.

For this multi-label learning setup, we follow the setting of [Fast Zero-Shot Image Tagging
](https://arxiv.org/pdf/1605.09759.pdf) which only trains and tests the model on the set of 81 ground-truth labels (as this label set has higher annotation quality than the 925 label set). Please refer to section 2.1 from our [suppmat](https://hbdat.github.io/pubs/suppmat_attentionZSL_final.pdf) for more detail.

Best,
Dat

**Comment by jingcaiguo** [comment]
> Hi @jingcaiguo ,
> 
> Thanks for reaching out.
> 
> The script "multilabel_experiments/NUS_WIDE_rank_Visual_Word_Attention.py" is used for multi-label learning (which we report in the supplementary material) and not the main multi-label zero-shot learning experiments.
> 
> For this multi-label learning setup, we follow the setting of [Fast Zero-Shot Image Tagging ](https://arxiv.org/pdf/1605.09759.pdf) which only trains and tests the model on the set of 81 ground-truth labels (as this label set has higher annotation quality than the 925 label set). Please refer to section 2.1 from our [suppmat](https://hbdat.github.io/pubs/suppmat_attentionZSL_final.pdf) for more detail.
> 
> Best,
> Dat

Thanks, Dat.

May I understand that the MZSL is to train the attention with (925 seen+81 unseen) word vectors with training images (seen classes), and to infer on testing 81 unseen class images (conventional mzsl) or testing full class images (generalized mzls)?

best,
JC.

**Comment by hbdat** [comment]
Hi @jingcaiguo ,

For the Multi-label Zero-Shot Learning setting, **_we only train the model on 925 seen labels_** and evaluate the model on 81 unseen labels for zero-shot performances or both seen and unseen labels (925+81 labels) for generalized zero-shot performances.

Best,
Dat
